spring.application.name=Todo-App

spring.datasource.url=jdbc:postgresql://dpg-d8v1to6q1p3s73bbud70-a.oregon-postgres.render.com:5432/todo_bxf3
spring.datasource.username=todo_bxf3_user
spring.datasource.password=EY4IqTEbketp3PBQkSs80uCBKQwJMYXr

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true